### ISSUE TITLE
Fatal Error: Class OsdxpModuleUpdateChecker' not found

### ISSUE THREAD

**Issue by XedinUnknown** [osDXP/osdxp-dashboard#18]
## The Symptom
After activating the plugin and reloading the page, I receive the following message:

```
Fatal error:  Uncaught Error: Class 'OSDXP_Dashboard\OsdxpModuleUpdateChecker' not found in includes/utils.php:31
  #0 /var/www/html/wp-includes/class-wp-hook.php(286): OSDXP_Dashboard\hook_update_check('')
  #1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
  #2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
  #3 /var/www/html/wp-settings.php(450): do_action('init')
  #4 /var/www/html/wp-config.php(88): require_once('/var/www/html/w...')
  #5 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
  #6 /var/www/html/wp-admin/admin.php(31): require_once('/var/www/html/w...')
  #7 /var/www/html/wp-admin/network/admin.php(13): require_once('/var/www/html/w...')
  #8 /var/www/html/wp-admin/network/plugins.php(11): require_once('/var/www/html/w...')
  #9 {main}
  thrown in includes/utils.php on line 31
```

## Possible Cause
The class files are not being loaded. The `includes` folder is [listed as a PSR-4 root][1], but none of the classes in this project follow PSR-4.

## Suggested Solution
- Switch to PSR-4. It is a much better and more widely used convention. Any convention, including PSR-4, would allow easier loading of classes without the need to generate autoload maps.
- Another option is to add `includes` as a [classmap][autoload-classmap] root instead of PSR-4. This will generate a map of all classes contained in all files in that folder, recursively, to their filename. It would require re-generation every time a new class is added, or a class file path is changed.

[1]: https://github.com/osDXP/osdxp-dashboard/blob/master/composer.json#L28
[autoload-classmap]: https://getcomposer.org/doc/04-schema.md#classmap

**Comment by al-esc** [comment]
hotfixed in [1.0.1](https://github.com/osDXP/osdxp-dashboard/releases/tag/v1.0.1), keeping this open since we need to switch to psr-4 rather than classmap

**Comment by XedinUnknown** [comment]
Oh, that would be wonderful! Let me know if there's something I can do to help in general.
